// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5OjksCu-hcEd-vlv7XcbjpxGzi-_JkPM',
    appId: '1:464466109983:web:3350f038baa5358582572a',
    messagingSenderId: '464466109983',
    projectId: 'blog-management-flutter',
    authDomain: 'blog-management-flutter.firebaseapp.com',
    databaseURL: 'https://blog-management-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'blog-management-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtW7mDKAPmuhXoD_mnBy2eStlmBgzUuQo',
    appId: '1:464466109983:android:ee33dedf9003f02882572a',
    messagingSenderId: '464466109983',
    projectId: 'blog-management-flutter',
    databaseURL: 'https://blog-management-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'blog-management-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf_Byiqx-tkAEKlvKuKQFEM_5QZUwhJyo',
    appId: '1:464466109983:ios:d65f670e710d9b6b82572a',
    messagingSenderId: '464466109983',
    projectId: 'blog-management-flutter',
    databaseURL: 'https://blog-management-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'blog-management-flutter.appspot.com',
    iosBundleId: 'com.example.blogManagement1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf_Byiqx-tkAEKlvKuKQFEM_5QZUwhJyo',
    appId: '1:464466109983:ios:50d06e69c5ce48e482572a',
    messagingSenderId: '464466109983',
    projectId: 'blog-management-flutter',
    databaseURL: 'https://blog-management-flutter-default-rtdb.firebaseio.com',
    storageBucket: 'blog-management-flutter.appspot.com',
    iosBundleId: 'com.example.blogManagement.RunnerTests',
  );
}
